### ISSUE TITLE
Build Error on Debian7.1

### ISSUE THREAD

**Issue by yukota** [sgvandijk/libbats#1]
I failed to make.
I did cmake . and make in root directory of libbats.
Error message said configure.hh is not found.
What should I do before cmake?

```
In file included from /home/libbats/HumanoidAgent/startUp.cc:1:0:
/home/libbats/HumanoidAgent/humanoidagent.ih:18:24: fatal error: configure.hh: そのようなファイルやディレクトリはありません
compilation terminated.
make[2]: *** [CMakeFiles/bats.dir/HumanoidAgent/startUp.cc.o] エラー 1
make[1]: *** [CMakeFiles/bats.dir/all] エラー 2
make: *** [all] エラー 2
```

**Comment by sgvandijk** [comment]
Thanks for opening the issue. The CMake directive to generate `configure.hh` had gone missing. I just pushed it again, please pull and check it out.

**Comment by yukota** [comment]
I checked.
Thank you.
