### ISSUE TITLE
 Compiling problem with libxml2

### ISSUE THREAD

**Issue by danialbehzadi** [sgvandijk/libbats#2]
Hi. I got the latest version of libbats(3.0) and I encountered an error during make it:
<code>Scanning dependencies of target helloworld
[ 95%] Building CXX object examples/helloworld/CMakeFiles/helloworld.dir/helloworld.cc.o
[ 96%] Building CXX object examples/helloworld/CMakeFiles/helloworld.dir/HelloWorldAgent/init.cc.o
[ 96%] Building CXX object examples/helloworld/CMakeFiles/helloworld.dir/HelloWorldAgent/think.cc.o
Linking CXX executable helloworld
../../libbats.so: undefined reference to `xmlCtxtUseOptions'
../../libbats.so: undefined reference to`xmlXPathFreeObject'
../../libbats.so: undefined reference to `xmlNewDoc'
../../libbats.so: undefined reference to`xmlXPathEvalExpression'
../../libbats.so: undefined reference to `xmlFree'
../../libbats.so: undefined reference to`xmlFreeDoc'
../../libbats.so: undefined reference to `xmlCreateFileParserCtxt'
../../libbats.so: undefined reference to`xmlResetLastError'
../../libbats.so: undefined reference to `xmlNodeGetContent'
../../libbats.so: undefined reference to`xmlCheckVersion'
../../libbats.so: undefined reference to `xmlCleanupParser'
../../libbats.so: undefined reference to`xmlHasProp'
../../libbats.so: undefined reference to `xmlXPathNewContext'
../../libbats.so: undefined reference to`xmlGetProp'
../../libbats.so: undefined reference to `xmlParserGetDirectory'
../../libbats.so: undefined reference to`xmlXPathFreeContext'
../../libbats.so: undefined reference to `xmlXIncludeProcessFlags'
../../libbats.so: undefined reference to`xmlParseDocument'
collect2: error: ld returned 1 exit status
make[2]: **\* [examples/helloworld/helloworld] Error 1
make[1]: **\* [examples/helloworld/CMakeFiles/helloworld.dir/all] Error 2
make: **\* [all] Error 2</code>

**Comment by sgvandijk** [comment]
The fix for this is included in the new release, v3.0.1
